# This search strategy does a multi_match prefix query to search in the title field of the documents.
PunktDe:
  Elastic:
    NodeSearchService:
      logRequests: true
      searchStrategies:
        titlePrefix:
          condition: '${Array.indexOf(searchNodeTypes, "Neos.Neos:Document") != -1}'
          request:
            query:
              bool:
                filter:
                  bool:
                    minimum_should_match: 1
                    should:
                      - multi_match:
                          query: ARGUMENT_TERM
                          type: bool_prefix
                          fields: ['punktde_node_search']
                    must:
                      - terms:
                          __typeAndSupertypes: ARGUMENT_SEARCHNODETYPES
                      - term:
                          __parentPath: ARGUMENT_STARTINGPOINT
                    must_not:
                      - term:
                          _hidden: true
            _source:
              - __path
            size: 20

