PunktDe:
  Elastic:
    NodeSearchService:
      logRequests: false
      searchStrategies:
        default:
          condition: '${true}'
          request:
            query:
              bool:
                filter:
                  bool:
                    minimum_should_match: 1
                    should:
                      - multi_match:
                          query: ARGUMENT_TERM
                          type: bool_prefix
                          fields: ['punktde_node_search', 'punktde_node_search._2gram', 'punktde_node_search._3gram']
                    must:
                      - terms:
                          __typeAndSupertypes: ARGUMENT_SEARCHNODETYPES
                      - term:
                          __parentPath: ARGUMENT_STARTINGPOINT
                    must_not:
                      - term:
                          _hidden: true
            _source:
              - __path
            size: 10

